import sys
import json
from pathlib import Path
from src.topos_visualizer import materialize_integrated_visualizer

def main():
    if len(sys.argv) < 2:
        print("Usage: python run_visualizer.py <path_to_cliff_output_folder>")
        sys.exit(1)

    target_dir = Path(sys.argv[1])
    
    # Locate the JSON artifacts generated by CLIFF
    cf_files = list(target_dir.rglob("*democritus_counterfactuals*.json"))
    psr_files = list(target_dir.rglob("*democritus_topos_psr_hankel*.json"))

    if not cf_files or not psr_files:
        print("[-] ERROR: Could not find required CLIFF JSON artifacts in the specified folder.")
        sys.exit(1)

    print(f"[*] Found CLIFF artifacts in {target_dir.name}. Generating Visualizer...")
    
    # Trigger the visualization engine
    out_file = materialize_integrated_visualizer(
        query=target_dir.name,
        route_outdir=target_dir,
        psr_path=psr_files[0],
        counterfactuals_path=cf_files[0]
    )
    
    print(f"[+] Success! Interactive Dashboard created at: {out_file}")

if __name__ == "__main__":
    main()
